apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # Matches the label of the pods from the deployment
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80   
  type: ClusterIP  
